environment:
  grid_size: 5
  forest_density: 0.9
  start_fires_num: 1
  losing_reward: -1000
  tree_fire_spread_prob: 1.0
  diagonal_tree_fire_spread_prob: 0.573
  trench_fire_spread_prob: 0.2
  diagonal_trench_fire_spread_prob: 0.1
  disable_fire_propagation: False
  control_line_cost: 3
  burnout_cost: 3
  firetruck_cost: 5
  helicopter_cost: 25
  firetruck_success_rate: 0.8
  helicopter_success_rate: 0.9
  firetruck_range: 1
  helicopter_range: 2

resources:
  budget: 36
  firefighters: 2
  firetrucks: 1
  helicopters: 1

rendering:
  render_mode: 'rgb_array' # 'human' or 'rgb_array' or 'none'
  render_fps: 4
  window_size: 500
